apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:gallery| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]Gallery[/b].
    Gallery is the open source web based photo album organizer.
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]Gallery![/b]
    To access [b]Gallery[/b] use this link: [url]http://%PUBLIC_ADDRESS%[/url]
    You can access [b]MySQL[/b] using credentials:
    [b]Host:[/b] 127.0.0.1
    [b]Database:[/b] gallery3
    [b]Login:[/b] gallery
    [b]Password:[/b]  $MYSQL_USER_PASSWORD$

    We recommend you to save the credentials.

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: gallery
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 5
            - name: gallery
              kubes: 1
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: gallery-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: gallery
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: gallery-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 4
            - name: gallery
              kubes: 1
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: gallery-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: gallery_mysql_$PD_RAND|default:autogen|PD rand$
        - name: gallery-persistent-storage
          persistentDisk:
            pdName: gallery_www_$PD_RAND$
      restartPolicy: "Always"
      containers:
        -
          name: mysql
          image: mysql:5
          env:
            - name: MYSQL_DATABASE
              value: gallery3
            - name: MYSQL_USER
              value: gallery
            - name: MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD|default:autogen|mysql user password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql root password$
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: gallery
          image: kuberdock/gallery3
          ports:
          - containerPort: 80
            isPublic: True
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/www/var
              name: gallery-persistent-storage
