apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:mantis| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]Mantis[/b].
    [b]Mantis[/b] is an open source issue tracker that provides a delicate balance between simplicity and power.
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]Mantis[/b]
    Please find more information about Mantis software on the official website [url]https://www.mantisbt.org/[/url]
    To access [b]Mantis[/b] use this link: [url]http://%PUBLIC_ADDRESS%[/url]
    You can access [b]MySQL[/b] using credentials:
    [b]Host:[/b] 127.0.0.1
    [b]Database:[/b] bugtracker
    [b]Login:[/b] mantis
    [b]Password:[/b]  $MYSQL_USER_PASSWORD$

    Please, read the application documentation: [url]https://www.mantisbt.org/documentation.php[/url]

    We recommend you to save the credentials.

    Please, restart pod after installation.

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: mantis
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 0
          containers:
            - name: mysql
              kubes: 6
            - name: mantis
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: mantis-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: mantis
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: mantis-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 6
            - name: mantis
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: mantis-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: mantis_mysql_$PD_RAND|default:autogen|PD rand$
        - name: mantis-persistent-storage
          persistentDisk:
            pdName: mantis_www_$PD_RAND$
      restartPolicy: "Always"
      containers:
        -
          name: mysql
          image: kuberdock/mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: bugtracker
            - name: MYSQL_USER
              value: mantis
            - name: MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD|default:autogen|mysql password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql password$
            - name: MYSQL_AUTO_MEMORY_ALLOCATE
              value: $MYSQL_AUTO_MEMORY_ALLOCATE|default:innodb|Please choose default MySQL engine "innodb" or "myisam"$
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: mantis
          image: kuberdock/mantisbt:1.3.1
          ports:
            - containerPort: 80
              isPublic: True
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/www/html
              name: mantis-persistent-storage
              kdCopyFromImage: true
          workingDir: /var/www/html

